{******************************************}
{                                          }
{             senCille v 1.0               }
{              Include file                }
{                                          }
{         Copyright (c) 2015               }
{    by Juan Carlos Cilleruelo Gonzalo     }
{             senCille.es                  }
{                                          }
{******************************************}

const SALT = '{E1D0658A-DD4E-4B41-8E22-A71EFFF446E2}';
      MAX_ACCESSES          = 500; {Half hundred by day}
      TEST_UNREG_DAYS       = 10;
      RootHelpPath = 'https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/The_OpenSCAD_Language';
      RootWebPath  = 'http://sencille.es/';

      MAJOR_VERSION         = '01';
      MINOR_VERSION         = '00';
  